### ISSUE TITLE
"n00b" Malware in sources

### ISSUE THREAD

**Issue by minebuild3543** [spongecattle/porty#11]
Greetings.
I hereby request the developer to inquiry the source code of his program's [_master_] branch, as there are possible cases of malware [_Virus.PortyWorm_] in [_programs/worm_] the repository.
Please pay attention to this as malware in the source code of a legitimate program may signify that either you have a malicious contributor or your account was hacked.
I wish you good luck.
Sincerely,
minebuild02
Head Developer of BLAST AntiMalware

**Comment by Lignum** [comment]
fakeeee

**Comment by Colean128** [comment]
Hello @minebuild3543 we have removed Virus/PortyWorm in #12  but possibly will re add it due to the fact your anti virus (i've tried it.) thinks EVERYTHING is a virus.

**Comment by Colean128** [comment]
Reverted in #13
